baseurl = "http://example.org/"
languageCode = "en-us"
title = "Junyeop Na Dev"
theme = "dream"

[params]
  author = "Jun Yeop Na"
  headerTitle = "Jun Yeop Na Dev Blog"
  favicon = "/images/favicon.svg"  # Change this path to your desired favicon location
  siteStartYear = 2024 
