baseURL = 'https://www.junyeopna.blog/'
languageCode = 'en-us'
title = 'Junyeop Na Dev'
theme = 'hugo-theme-dream'

images = ["image/co-detr.png"]

author = 'junyeopna'
description = 'Jun Yeop Na ML BLog'
headerTitle = 'Jun Yeop Na ML Blog'

[params]
  author = "Junyeop Na"
  headerTitle = "Junyeop Na Dev Blog"
  favicon = "/images/favicon.svg"  # Change this path to your desired favicon location
  avatar = "/images/favicon.svg"
  siteStartYear = 2024 
